spring:
  h2:
    console:
      enabled: true
      path: /h2
#  datasource:
#    url: jdbc:h2:mem:test #h2 이용
  datasource:
#    url: ${datasource_url}
#    username: ${datasource_username}
#    password: ${datasource_password}
    url: jdbc:mysql://{AWS RDS Endpoint}/test?useSSL=false&characterEncoding=UTF-8&serve
    username: {RDS Mysql Admin id}
    password: {RDS Mysql Admin password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    domain: {AWS S3 Endpoint}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    show-sql: true      # (2) SQL 쿼리 출력
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print
        highlight_sql: true
        color-codes: true
        use_sql_comments: true
    defer-datasource-initialization: true # 더미데이터 전 테이블 부터 만듦

  sql:
    init:
      data-locations: classpath*:db/h2/data.sql # 더미데이터
      mode: always # 더미데이터 관련
      platform: h2
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${G_CLIENT_ID}
            clientSecret: ${G_CLIENT_SECRET}
            scope:
              - email
              - profile
          github:
            clientId: ${H_CLIENT_ID}
            clientSecret: ${H_CLIENT_SECRET}

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace;
      springframework:
        orm:
          jpa: DEBUG

mail:
  address:
    admin: admin@gmail.com
  smtp:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}  # 민감한 정보는 시스템 환경 변수로..
    password: ${EMAIL_PASSWORD}  # 민감한 정보는 시스템 환경 변수로..
    auth: true
    starttls:
      enable: true
  subject:
      member:
        registration: 스택오버플로우 가입 축하!
  template:
      name:
        member:
          join: email-registration-member

jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 30 #30분.
  refresh-token-expiration-minutes: 420 # 420분

server:
  servlet:
    encoding:
      force-response: true




